### ISSUE TITLE
README.md is not up to date

### ISSUE THREAD

**Issue by matsjoonas** [web-eid/web-eid-webextension#30]
Should this line:
https://github.com/web-eid/web-eid-webextension/blob/main/README.md?plain=1#L19
actually be:
`git clone --recurse-submodules git@github.com:web-eid/web-eid-webextension.git`
?
Since the public repo is on github and you are using submodules.

**Comment by mrts** [comment]
@matsjoonas thank you for the correction! Yes, right you are, I will fix the README promptly.

**Comment by mrts** [comment]
Fixed in https://github.com/web-eid/web-eid-webextension/commit/5e030111de8ff31ad27d4fc1c0f2678010cbe60a
