### ISSUE TITLE
Consent screen in Firefox interferes with browser automation

### ISSUE THREAD

**Issue by ragulka** [web-eid/web-eid-webextension#56]
The `views/installed` screen is always shown in Firefox [when the `onInstalled` event fires](https://github.com/web-eid/web-eid-webextension/blob/351a0cb491bd8ef9506ac85a6fe4742fb45b3fb1/src/background/background.ts#L111C2-L116).

This seems to interfere with browser automation when using browser automation (Selenium / geckodriver, etc), as this screen is shown every time the browser starts - which can happen multiple times during a testsuite. 

The way browser automation tests work is that a temporary, empty profile is created for the browser for running the tests to ensure extensions do not interfere with them. However, for some reason, Web eID consistently keeps popping up as the only installed extension during automation.

I have tried disabling the extension on my Firefox profile, as well as completely removing it, but it still pops up when running browser tests. I am not proficient enough in browser extensions to understand why this happens. It almost feels like it's force-installed for each new Firefox profile?

## Steps to reproduce

1. Set up a minimal test which involves browser automation, for example using https://github.com/derekmd/laravel-dusk-firefox
2. Run the test
3. Every time the test runs, the consent screen pops up:

<img width="1285" alt="CleanShot 2023-07-06 at 14 13 20@2x" src="https://github.com/web-eid/web-eid-webextension/assets/593267/e30c9c3c-05e6-41db-ac9f-26b884b49be0">

## Ideas

Perhaps it would be possible to detect if the browser is being run by automation software and skip showing the consent screen in such cases?

**Comment by mrts** [comment]
Hi @ragulka! 

If you select Web eID Firefox support during installation, the installer forces extension loading in Firefox by a special registry key (see below).

There are two ways to get rid of the extension:

1. Uninstall Web eID Firefox support using the official installer, or
2. Manually remove the registry key that forces extension loading in Firefox. The key is JSON-encoded inside `HKLM\Software\Policies\Mozilla\Firefox\ExtensionSettings` and you only need to remove the entry that starts with `"{e68418bc-f2b0-4459-a9ea-3e72b6751b07}"`. So, given the following initial value of `ExtensionSettings` with multiple entries:  
    ```json
    {
      "{e68418bc-f2b0-4459-a9ea-3e72b6751b07}": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/web-eid-webextension/latest.xpi"
      },
      "{02274e0c-d135-45f0-8a9c-32b35110e10d}": {
        "installation_mode": "blocked"
      }
    }
    ```

here's how the result should look like after you remove `"{e68418bc-f2b0-4459-a9ea-3e72b6751b07}"`: 

```json
    {
      "{02274e0c-d135-45f0-8a9c-32b35110e10d}": {
        "installation_mode": "blocked"
      }
    }
```

Closing, please feel free to reopen if you have further questions.

**Comment by ragulka** [comment]
@mrts what about when using MacOS?
