### ISSUE TITLE
Latest version as of 2023-09-13

### ISSUE THREAD

**Issue by sskras** [web-eid/web-eid-webextension#63]
What is the latest available **version of Web-eID** web-extension for Chrome?

My Chrome shows version **2.2.0** installed: `chrome://extensions/?id=ncibgoaomkmdpilpocfeponihegamlic`

![image](https://github.com/web-eid/web-eid-webextension/assets/7887758/b51c45f3-8efb-474b-8ce8-870deb1bea3e)

And your [web page](https://web-eid.eu/#:~:text=Firefox%2C%20Chrome%20and%20Edge%20from%20here) mentions version [**2.4.0**.639](https://installer.id.ee/media/web-eid/web-eid_2.4.0.639.x64.exe):

![image](https://github.com/web-eid/web-eid-webextension/assets/7887758/d0c44a27-3b42-400b-8963-8325e0c0ee13)

---

I am confused by this difference: **2.2.0** vs **2.4.0**.639

**Comment by kristelmerilain** [comment]
Hello!

Latest available version of Web eID browser extension for Chrome is 2.2.0.
Web eID application version is 2.4.0, which is mentioned on web-eid.eu page.

You can find Web eID browser extension releases from [here](https://github.com/web-eid/web-eid-webextension/releases) and Web eID application releases from [here](https://github.com/web-eid/web-eid-app).

**Comment by sskras** [comment]
@kristelmerilain commented [41 minutes ago](https://github.com/web-eid/web-eid-webextension/issues/63#issuecomment-1718806952):

> Latest available version of Web eID browser extension for Chrome is 2.2.0. Web eID application version is 2.4.0, which is mentioned on web-eid.eu page.

Thanks. Aren't the version number correlated between these two projects?

> You can find Web eID browser extension releases from [here](https://github.com/web-eid/web-eid-webextension/releases) and Web eID application releases from [here](https://github.com/web-eid/web-eid-app).

I also would like to clarify about the latter:

is the **Web eID application** a kind of backend, the server side software?

**Comment by sskras** [comment]
PS. I am asking about this because Lithuanian ID-cards released after 2021-08-12 aren't accepted by the Smart-ID system at the moment.
The Smart-ID support said that the blocker is the **Web eID** software which needs to be updated.

I am trying to find out the newest versions and the right repo out of all the components.
So I get nearer to the root cause.
